### ISSUE TITLE
AttributeError: 'list' object has no attribute 'check_finished'

### ISSUE THREAD

**Issue by chunweizhu** [deepmodeling/APEX#57]
phonon caculation with dp potential

- apex-flow version 1.1.4

~~~sh
apex test relaxation.json make_relax
apex test relaxation.json run_relax -m machine.json
apex test relaxation.json post_relax 

apex test property.json make_props
apex test property.json run_props -m machine.json    ###error
apex test property.json post_props
~~~

# Error
~~~sh
Run property tasks locally...
Submit job via 1 processes
Traceback (most recent call last):
  File "/share/home/zhucw/.conda/envs/deepmd222/bin/apex", line 8, in <module>
    sys.exit(main())
  File "/share/home/zhucw/.conda/envs/deepmd222/lib/python3.10/site-packages/apex/main.py", line 115, in main
    run_step(
  File "/share/home/zhucw/.conda/envs/deepmd222/lib/python3.10/site-packages/apex/run_step.py", line 56, in run_step
    run_property(structures, inter_parameter, param, mdata)
  File "/share/home/zhucw/.conda/envs/deepmd222/lib/python3.10/site-packages/apex/core/common_prop.py", line 196, in run_property
    run_tasks = collect_task(all_task, inter_type)
  File "/share/home/zhucw/.conda/envs/deepmd222/lib/python3.10/site-packages/apex/core/lib/util.py", line 105, in collect_task
    check_finished = lammps_task_type.check_finished
AttributeError: 'list' object has no attribute 'check_finished'
~~~

https://github.com/deepmodeling/APEX/blob/c42776681826293f82a071e874a88cb949af9507/apex/core/lib/util.py#L105

# BUG
~~~python
        #check_finished = lammps_task_type.check_finished
        check_finished = lammps_utils.check_finished
~~~

**Comment by chunweizhu** [comment]
**NEW ERROR** 
~~~sh
Traceback (most recent call last):
  File "/share/home/zhucw/.conda/envs/deepmd222/lib/python3.10/site-packages/dpdispatcher/submission.py", line 273, in try_download_result
    self.download_jobs()
  File "/share/home/zhucw/.conda/envs/deepmd222/lib/python3.10/site-packages/dpdispatcher/submission.py", line 501, in download_jobs
    self.machine.context.download(self)
  File "/share/home/zhucw/.conda/envs/deepmd222/lib/python3.10/site-packages/dpdispatcher/local_context.py", line 175, in download
    raise RuntimeError("do not find download file " + rfile)
RuntimeError: do not find download file /share/home/zhucw/phonon-test/phonon_lammps_apex/work/55d48b0dadc2b2d6701f21056f6cdca3cff8f6f6/task.000000/dump.relax
~~~

**Comment by ZLI-afk** [comment]
Please try to update `apex-flow>=1.1.5` that fixed this issue. Thanks.

**Comment by chunweizhu** [comment]
Thanks for the reply.
The solution is：
`machine.json`
~~~json
{
     "run_command": "phonolammps in.lammps -c POSCAR --dim * * * ", # Change this line 
}
~~~
