### ISSUE TITLE
problem with “RuntimeError: Workflow failed (ID: vasp-demo-relax-9vqes, UID: None)”

### ISSUE THREAD

**Issue by 919607** [deepmodeling/APEX#67]
This is the error I encountered after testing the relax of example/vasp_demo. How can I solve this problem? Currently, the calculation is being performed on an offline HPC. 
    In addition, may I ask why the output file during calculation is in the tmp folder instead of the current working directory? Only after the task is successful will the output file be returned to the current working directory. If the task fails, all the files generated by the calculation will be deleted by the tmp folder itself. Therefore, which parameter should I modify so that the real-time calculation results can be seen in the current directory.

[global_cpu_vasp.json](https://github.com/deepmodeling/APEX/files/15282103/global_cpu_vasp.json)
[script.json](https://github.com/deepmodeling/APEX/files/15282113/script.json)

```python
Checking input files...
-------Submit Workflow Mode-------
Running APEX calculation via vasp
Submitting relax workflow...
INFO:root:Working on: /public/home/DFT/MWang/test/APEX/vasp_demo
Workflow is running locally (ID: vasp-demo-relax-gi6sc)
INFO:root:Step RelaxVASP-Cal with item 0 starts in process 2527
2024-05-11 15:46:35,594 - INFO : info:check_all_finished: False
2024-05-11 15:46:35,614 - INFO : job: 27af331da087cdff12956ed1bd3c04d79f87eac8 submit; job_id is 728
2024-05-11 15:46:36,641 - INFO : job: 27af331da087cdff12956ed1bd3c04d79f87eac8 728 terminated; fail_cout is 1; resubmitting job
2024-05-11 15:46:36,662 - INFO : job:27af331da087cdff12956ed1bd3c04d79f87eac8 re-submit after terminated; new job_id is 729
2024-05-11 15:46:36,888 - INFO : job:27af331da087cdff12956ed1bd3c04d79f87eac8 job_id:729 after re-submitting; the state now is <JobStatus.waiting: 2>
2024-05-11 15:47:06,931 - INFO : job: 27af331da087cdff12956ed1bd3c04d79f87eac8 729 terminated; fail_cout is 2; resubmitting job
2024-05-11 15:47:06,968 - INFO : job:27af331da087cdff12956ed1bd3c04d79f87eac8 re-submit after terminated; new job_id is 730
2024-05-11 15:47:07,199 - INFO : job:27af331da087cdff12956ed1bd3c04d79f87eac8 job_id:730 after re-submitting; the state now is <JobStatus.waiting: 2>
2024-05-11 15:47:37,241 - INFO : job: 27af331da087cdff12956ed1bd3c04d79f87eac8 730 terminated; fail_cout is 3; resubmitting job
Traceback (most recent call last):
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dpdispatcher/submission.py", line 358, in handle_unexpected_submission_state
    job.handle_unexpected_job_state()
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dpdispatcher/submission.py", line 862, in handle_unexpected_job_state
    raise RuntimeError(err_msg)
RuntimeError: job:27af331da087cdff12956ed1bd3c04d79f87eac8 730 failed 3 times.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/tmpc0aq6d1q/vasp-demo-relax-gi6sc/relaxflow--relax--run-0-vasp/script", line 71, in <module>
    submission.run_submission(clean=True)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dpdispatcher/submission.py", line 261, in run_submission
    self.handle_unexpected_submission_state()
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dpdispatcher/submission.py", line 362, in handle_unexpected_submission_state
    raise RuntimeError(
RuntimeError: Meet errors will handle unexpected submission state.
Debug information: remote_root==/tmp/tmpc0aq6d1q/vasp-demo-relax-gi6sc/relaxflow--relax--run-0-vasp/workdir/..
Debug information: submission_hash==9014adac79074eabd5d242253c4b16a15e781d3e.
Please check error messages above and in remote_root. The submission information is saved in /public/home/.dpdispatcher/submission/9014adac79074eabd5d242253c4b16a15e781d3e.json.
For furthur actions, run the following command with proper flags: dpdisp submission 9014adac79074eabd5d242253c4b16a15e781d3e
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/public/home/local/anaconda3/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 2090, in exec_with_config
    self.exec(scope, parameters, item, context)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 1782, in exec
    self.exec_pod(scope, parameters, item)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 2023, in exec_pod
    raise RuntimeError("Run %s failed" % args)
RuntimeError: Run ['python3', '/tmp/tmpc0aq6d1q/vasp-demo-relax-gi6sc/relaxflow--relax--run-0-vasp/script'] failed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 1562, in run
    ps = future.result()
  File "/public/home/local/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/public/home/local/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
RuntimeError: Run ['python3', '/tmp/tmpc0aq6d1q/vasp-demo-relax-gi6sc/relaxflow--relax--run-0-vasp/script'] failed
INFO:root:Step RelaxVASP-Cal with item 1 starts in process 2527
2024-05-11 15:47:39,397 - INFO : info:check_all_finished: False
2024-05-11 15:47:39,430 - INFO : job: 9acb6090d3fc18df2eb3b87b4997a662bb9ebf97 submit; job_id is 731
2024-05-11 15:47:40,465 - INFO : job: 9acb6090d3fc18df2eb3b87b4997a662bb9ebf97 731 terminated; fail_cout is 1; resubmitting job
2024-05-11 15:47:40,498 - INFO : job:9acb6090d3fc18df2eb3b87b4997a662bb9ebf97 re-submit after terminated; new job_id is 732
2024-05-11 15:47:40,727 - INFO : job:9acb6090d3fc18df2eb3b87b4997a662bb9ebf97 job_id:732 after re-submitting; the state now is <JobStatus.waiting: 2>
2024-05-11 15:48:10,788 - INFO : job: 9acb6090d3fc18df2eb3b87b4997a662bb9ebf97 732 terminated; fail_cout is 2; resubmitting job
2024-05-11 15:48:10,825 - INFO : job:9acb6090d3fc18df2eb3b87b4997a662bb9ebf97 re-submit after terminated; new job_id is 733
2024-05-11 15:48:11,056 - INFO : job:9acb6090d3fc18df2eb3b87b4997a662bb9ebf97 job_id:733 after re-submitting; the state now is <JobStatus.waiting: 2>
2024-05-11 15:48:41,100 - INFO : job: 9acb6090d3fc18df2eb3b87b4997a662bb9ebf97 733 terminated; fail_cout is 3; resubmitting job
Traceback (most recent call last):
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dpdispatcher/submission.py", line 358, in handle_unexpected_submission_state
    job.handle_unexpected_job_state()
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dpdispatcher/submission.py", line 862, in handle_unexpected_job_state
    raise RuntimeError(err_msg)
RuntimeError: job:9acb6090d3fc18df2eb3b87b4997a662bb9ebf97 733 failed 3 times.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/tmpc0aq6d1q/vasp-demo-relax-gi6sc/relaxflow--relax--run-1-vasp/script", line 71, in <module>
    submission.run_submission(clean=True)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dpdispatcher/submission.py", line 261, in run_submission
    self.handle_unexpected_submission_state()
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dpdispatcher/submission.py", line 362, in handle_unexpected_submission_state
    raise RuntimeError(
RuntimeError: Meet errors will handle unexpected submission state.
Debug information: remote_root==/tmp/tmpc0aq6d1q/vasp-demo-relax-gi6sc/relaxflow--relax--run-1-vasp/workdir/..
Debug information: submission_hash==1710433776d07e0b198419ccf6f1944e74a28dfc.
Please check error messages above and in remote_root. The submission information is saved in /public/home/.dpdispatcher/submission/1710433776d07e0b198419ccf6f1944e74a28dfc.json.
For furthur actions, run the following command with proper flags: dpdisp submission 1710433776d07e0b198419ccf6f1944e74a28dfc
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/public/home/local/anaconda3/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 2090, in exec_with_config
    self.exec(scope, parameters, item, context)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 1782, in exec
    self.exec_pod(scope, parameters, item)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 2023, in exec_pod
    raise RuntimeError("Run %s failed" % args)
RuntimeError: Run ['python3', '/tmp/tmpc0aq6d1q/vasp-demo-relax-gi6sc/relaxflow--relax--run-1-vasp/script'] failed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 1562, in run
    ps = future.result()
  File "/public/home/local/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/public/home/local/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
RuntimeError: Run ['python3', '/tmp/tmpc0aq6d1q/vasp-demo-relax-gi6sc/relaxflow--relax--run-1-vasp/script'] failed
Traceback (most recent call last):
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 1847, in exec_steps
    steps.run(scope.workflow_id, context)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/steps.py", line 285, in run
    step.run(self, context)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 1579, in run
    raise RuntimeError("Step %s failed" % failed)
RuntimeError: Step [RelaxVASP-Cal, RelaxVASP-Cal] failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 1603, in run
    self.exec(scope, parameters, context)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 1780, in exec
    self.exec_steps(scope, parameters, item, context)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 1852, in exec_steps
    raise RuntimeError("Step %s failed" % self)
RuntimeError: Step relaxation-cal failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/workflow.py", line 335, in submit
    entrypoint.run(self.id, self.context)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/steps.py", line 285, in run
    step.run(self, context)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/dflow/step.py", line 1607, in run
    raise RuntimeError("Step %s failed" % self)
RuntimeError: Step relaxation-cal failed
Waiting for relaxation result...
Traceback (most recent call last):
  File "/public/home/local/anaconda3/bin/apex", line 8, in <module>
    sys.exit(main())
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/apex/main.py", line 529, in main
    submit_from_args(
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/apex/submit.py", line 292, in submit_from_args
    submit_workflow(
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/apex/submit.py", line 269, in submit_workflow
    submit(
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/apex/submit.py", line 144, in submit
    flow_id = flow.submit_relax(
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/apex/utils.py", line 311, in wrapper
    result = function(*tuple(args), **kwargs)
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/apex/flow.py", line 287, in submit_relax
    self._monitor_relax()
  File "/public/home/local/anaconda3/lib/python3.9/site-packages/apex/flow.py", line 96, in _monitor_relax
    raise RuntimeError(f'Workflow failed (ID: {self.workflow.id}, UID: {self.workflow.uid})')
RuntimeError: Workflow failed (ID: vasp-demo-relax-gi6sc, UID: None)
```

**Comment by ZLI-afk** [comment]
Sorry for the late reply to your issue.
1. You may need to check specific VASP calculation failure msg by visiting:
'''
The submission information is saved in /public/home/.dpdispatcher/submission/1710433776d07e0b198419ccf6f1944e74a28dfc.json
'''
2. Yes, with the dflow mode, your output results will only be retrieved to current workspace after finish of specific sub-workflow. You may need to set `clean_asynchronously` to be `false` within the global configuration json file to close this auto-cleaning function

**Comment by 919607** [comment]
Thank you very much for your suggestion. Currently, it seems that the submission task failed due to permission issues with /tmp. Once I set "debug_workdir" : "./", I can submit the relaxation task

**Comment by 919607** [comment]
> Sorry for the late reply to your issue.
> 
> 1. You may need to check specific VASP calculation failure msg by visiting:
> 
> ```
> The submission information is saved in /public/home/.dpdispatcher/submission/1710433776d07e0b198419ccf6f1944e74a28dfc.json
> ```
> 
> 2. Yes, with the dflow mode, your output results will only be retrieved to current workspace after finish of specific sub-workflow. You may need to set `clean_asynchronously` to be `false` within the global configuration json file to close this auto-cleaning function

Thank you very much for your suggestion. Currently, it seems that the submission task failed due to permission issues with `/tmp`. Once I set `"debug_workdir" : "./"`, I can submit the relaxation task

**Comment by 919607** [comment]
Thank you very much for your suggestion. Currently, it seems that the submission task failed due to permission issues with `/tmp`. Once I set `"debug_workdir" : "./"`, I can submit the relaxation task
